### ISSUE TITLE
Error at My Account page 

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#669]
Fatal error: Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Overrides\OrderRefund::get_view_order_url() in /home/dev/public_html/mvx1/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-order.php:1308 Stack trace: #0 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): MVX_Order->woocommerce_my_account_my_orders_column_mvx_suborder() #1 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/dev/public_html/mvx1/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/templates/myaccount/orders.php(45): do_action() #4 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...') #5 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3291): wc_get_template() #6 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): woocommerce_account_orders() #7 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #8 /home/dev/public_html/mvx1/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3239): do_action() #10 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): woocommerce_account_content() #11 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #12 /home/dev/public_html/mvx1/wp-includes/plugin.php(517): WP_Hook->do_action() #13 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/templates/myaccount/my-account.php(34): do_action() #14 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('...') #15 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(123): wc_get_template() #16 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(72): WC_Shortcode_My_Account::my_account() #17 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_My_Account::output() #18 /home/dev/public_html/mvx1/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(115): WC_Shortcodes::shortcode_wrapper() #19 /home/dev/public_html/mvx1/wp-includes/shortcodes.php(433): WC_Shortcodes::my_account() #20 [internal function]: do_shortcode_tag() #21 /home/dev/public_html/mvx1/wp-includes/shortcodes.php(273): preg_replace_callback() #22 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): do_shortcode() #23 /home/dev/public_html/mvx1/wp-includes/plugin.php(205): WP_Hook->apply_filters() #24 /home/dev/public_html/mvx1/wp-includes/post-template.php(256): apply_filters() #25 /home/dev/public_html/mvx1/wp-content/themes/storefront/inc/storefront-template-functions.php(352): the_content() #26 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): storefront_page_content() #27 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #28 /home/dev/public_html/mvx1/wp-includes/plugin.php(517): WP_Hook->do_action() #29 /home/dev/public_html/mvx1/wp-content/themes/storefront/content-page.php(18): do_action() #30 /home/dev/public_html/mvx1/wp-includes/template.php(792): require('...') #31 /home/dev/public_html/mvx1/wp-includes/template.php(725): load_template() #32 /home/dev/public_html/mvx1/wp-includes/general-template.php(206): locate_template() #33 /home/dev/public_html/mvx1/wp-content/themes/storefront/page.php(24): get_template_part() #34 /home/dev/public_html/mvx1/wp-includes/template-loader.php(106): include('...') #35 /home/dev/public_html/mvx1/wp-blog-header.php(19): require_once('...') #36 /home/dev/public_html/mvx1/index.php(17): require('...') #37 {main} thrown in /home/dev/public_html/mvx1/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-order.php on line 1308

**Comment by moumitahalder** [comment]
Fatal error: Uncaught Error: Call to a member function add_order_note() on bool in /home/dev/public_html/mvx1/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-order.php:1610 Stack trace: #0 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(324): MVX_Order->mvx_handler_cust_requested_refund() #1 /home/dev/public_html/mvx1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #2 /home/dev/public_html/mvx1/wp-includes/plugin.php(565): WP_Hook->do_action() #3 /home/dev/public_html/mvx1/wp-includes/class-wp.php(830): do_action_ref_array() #4 /home/dev/public_html/mvx1/wp-includes/functions.php(1336): WP->main() #5 /home/dev/public_html/mvx1/wp-blog-header.php(16): wp() #6 /home/dev/public_html/mvx1/index.php(17): require('...') #7 {main} thrown in /home/dev/public_html/mvx1/wp-content/plugins/dc-woocommerce-multi-vendor/classes/class-mvx-order.php on line 1610
